### ISSUE TITLE
Shop Villager is a normal vanilla shop after Restart

### ISSUE THREAD

**Issue by bleihof** [DosMike/VillagerShops#67] opened 2019-09-16 17:48 UTC
When I create a shop and restart the server, it's not a shop villager anymore but a normal Minecraft Villager.

error:
[19:36:31] [Server thread/INFO] [vshop]: Registering commands...
[19:36:31] [Server thread/INFO] [STDERR]: [de.dosmike.sponge.vshop.VillagerShops:loadShops:269]: ninja.leaping.configurate.objectmapping.ObjectMappingException: Could not translate DataSerializable of type: org.spongepowered.api.item.inventory.ItemStack
[19:36:31] [Server thread/INFO] [STDERR]: [de.dosmike.sponge.vshop.VillagerShops:loadShops:269]: 	at org.spongepowered.common.config.DataSerializableTypeSerializer.lambda$deserialize$0(DataSerializableTypeSerializer.java:51)
[19:36:31] [Server thread/INFO] [STDERR]: [de.dosmike.sponge.vshop.VillagerShops:loadShops:269]: 	at java.util.Optional.orElseThrow(Optional.java:290)
[19:36:31] [Server thread/INFO] [STDERR]: [de.dosmike.sponge.vshop.VillagerShops:loadShops:269]: 	at org.spongepowered.common.config.DataSerializableTypeSerializer.deserialize(DataSerializableTypeSerializer.java:51)
[19:36:31] [Server thread/INFO] [STDERR]: [de.dosmike.sponge.vshop.VillagerShops:loadShops:269]: 	at org.spongepowered.common.config.DataSerializableTypeSerializer.deserialize(DataSerializableTypeSerializer.java:41)
[19:36:31] [Server thread/INFO] [STDERR]: [de.dosmike.sponge.vshop.VillagerShops:loadShops:269]: 	at ninja.leaping.configurate.SimpleConfigurationNode.getValue(SimpleConfigurationNode.java:218)
[19:36:31] [Server thread/INFO] [STDERR]: [de.dosmike.sponge.vshop.VillagerShops:loadShops:269]: 	at ninja.leaping.configurate.ConfigurationNode.getValue(ConfigurationNode.java:491)
[19:36:31] [Server thread/INFO] [STDERR]: [de.dosmike.sponge.vshop.VillagerShops:loadShops:269]: 	at de.dosmike.sponge.vshop.shops.StockItemSerializer.deserialize(StockItemSerializer.java:43)
[19:36:31] [Server thread/INFO] [STDERR]: [de.dosmike.sponge.vshop.VillagerShops:loadShops:269]: 	at de.dosmike.sponge.vshop.shops.StockItemSerializer.deserialize(StockItemSerializer.java:10)
[19:36:31] [Server thread/INFO] [STDERR]: [de.dosmike.sponge.vshop.VillagerShops:loadShops:269]: 	at ninja.leaping.configurate.objectmapping.serialize.TypeSerializers$ListSerializer.deserialize(TypeSerializers.java:250)
[19:36:31] [Server thread/INFO] [STDERR]: [de.dosmike.sponge.vshop.VillagerShops:loadShops:269]: 	at ninja.leaping.configurate.objectmapping.serialize.TypeSerializers$ListSerializer.deserialize(TypeSerializers.java:234)
[19:36:31] [Server thread/INFO] [STDERR]: [de.dosmike.sponge.vshop.VillagerShops:loadShops:269]: 	at ninja.leaping.configurate.SimpleConfigurationNode.getValue(SimpleConfigurationNode.java:218)
[19:36:31] [Server thread/INFO] [STDERR]: [de.dosmike.sponge.vshop.VillagerShops:loadShops:269]: 	at ninja.leaping.configurate.ConfigurationNode.getValue(ConfigurationNode.java:491)
[19:36:31] [Server thread/INFO] [STDERR]: [de.dosmike.sponge.vshop.VillagerShops:loadShops:269]: 	at de.dosmike.sponge.vshop.shops.NPCguardSerializer.deserialize(NPCguardSerializer.java:51)
[19:36:31] [Server thread/INFO] [STDERR]: [de.dosmike.sponge.vshop.VillagerShops:loadShops:269]: 	at de.dosmike.sponge.vshop.shops.NPCguardSerializer.deserialize(NPCguardSerializer.java:19)
[19:36:31] [Server thread/INFO] [STDERR]: [de.dosmike.sponge.vshop.VillagerShops:loadShops:269]: 	at ninja.leaping.configurate.objectmapping.serialize.TypeSerializers$ListSerializer.deserialize(TypeSerializers.java:250)
[19:36:31] [Server thread/INFO] [STDERR]: [de.dosmike.sponge.vshop.VillagerShops:loadShops:269]: 	at ninja.leaping.configurate.objectmapping.serialize.TypeSerializers$ListSerializer.deserialize(TypeSerializers.java:234)
[19:36:31] [Server thread/INFO] [STDERR]: [de.dosmike.sponge.vshop.VillagerShops:loadShops:269]: 	at ninja.leaping.configurate.SimpleConfigurationNode.getValue(SimpleConfigurationNode.java:218)
[19:36:31] [Server thread/INFO] [STDERR]: [de.dosmike.sponge.vshop.VillagerShops:loadShops:269]: 	at ninja.leaping.configurate.ConfigurationNode.getValue(ConfigurationNode.java:491)
[19:36:31] [Server thread/INFO] [STDERR]: [de.dosmike.sponge.vshop.VillagerShops:loadShops:269]: 	at de.dosmike.sponge.vshop.VillagerShops.loadShops(VillagerShops.java:266)
[19:36:31] [Server thread/INFO] [STDERR]: [de.dosmike.sponge.vshop.VillagerShops:loadShops:269]: 	at de.dosmike.sponge.vshop.VillagerShops.onServerStart(VillagerShops.java:194)
[19:36:31] [Server thread/INFO] [STDERR]: [de.dosmike.sponge.vshop.VillagerShops:loadShops:269]: 	at org.spongepowered.common.event.listener.GameStartedServerEventListener_VillagerShops_onServerStart99.handle(Unknown Source)
[19:36:31] [Server thread/INFO] [STDERR]: [de.dosmike.sponge.vshop.VillagerShops:loadShops:269]: 	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95)
[19:36:31] [Server thread/INFO] [STDERR]: [de.dosmike.sponge.vshop.VillagerShops:loadShops:269]: 	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:381)
[19:36:31] [Server thread/INFO] [STDERR]: [de.dosmike.sponge.vshop.VillagerShops:loadShops:269]: 	at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:454)
[19:36:31] [Server thread/INFO] [STDERR]: [de.dosmike.sponge.vshop.VillagerShops:loadShops:269]: 	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:415)
[19:36:31] [Server thread/INFO] [STDERR]: [de.dosmike.sponge.vshop.VillagerShops:loadShops:269]: 	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:253)
[19:36:31] [Server thread/INFO] [STDERR]: [de.dosmike.sponge.vshop.VillagerShops:loadShops:269]: 	at org.spongepowered.mod.SpongeMod.onStateEvent(SpongeMod.java:374)
[19:36:31] [Server thread/INFO] [STDERR]: [de.dosmike.sponge.vshop.VillagerShops:loadShops:269]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:36:31] [Server thread/INFO] [STDERR]: [de.dosmike.sponge.vshop.VillagerShops:loadShops:269]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[19:36:31] [Server thread/INFO] [STDERR]: [de.dosmike.sponge.vshop.VillagerShops:loadShops:269]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:36:31] [Server thread/INFO] [STDERR]: [de.dosmike.sponge.vshop.VillagerShops:loadShops:269]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[19:36:31] [Server thread/INFO] [STDERR]: [de.dosmike.sponge.vshop.VillagerShops:loadShops:269]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[19:36:31] [Server thread/INFO] [STDERR]: [de.dosmike.sponge.vshop.VillagerShops:loadShops:269]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[19:36:31] [Server thread/INFO] [STDERR]: [de.dosmike.sponge.vshop.VillagerShops:loadShops:269]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[19:36:31] [Server thread/INFO] [STDERR]: [de.dosmike.sponge.vshop.VillagerShops:loadShops:269]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[19:36:31] [Server thread/INFO] [STDERR]: [de.dosmike.sponge.vshop.VillagerShops:loadShops:269]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[19:36:31] [Server thread/INFO] [STDERR]: [de.dosmike.sponge.vshop.VillagerShops:loadShops:269]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[19:36:31] [Server thread/INFO] [STDERR]: [de.dosmike.sponge.vshop.VillagerShops:loadShops:269]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[19:36:31] [Server thread/INFO] [STDERR]: [de.dosmike.sponge.vshop.VillagerShops:loadShops:269]: 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
[19:36:31] [Server thread/INFO] [STDERR]: [de.dosmike.sponge.vshop.VillagerShops:loadShops:269]: 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
[19:36:31] [Server thread/INFO] [STDERR]: [de.dosmike.sponge.vshop.VillagerShops:loadShops:269]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:36:31] [Server thread/INFO] [STDERR]: [de.dosmike.sponge.vshop.VillagerShops:loadShops:269]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[19:36:31] [Server thread/INFO] [STDERR]: [de.dosmike.sponge.vshop.VillagerShops:loadShops:269]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:36:31] [Server thread/INFO] [STDERR]: [de.dosmike.sponge.vshop.VillagerShops:loadShops:269]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[19:36:31] [Server thread/INFO] [STDERR]: [de.dosmike.sponge.vshop.VillagerShops:loadShops:269]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[19:36:31] [Server thread/INFO] [STDERR]: [de.dosmike.sponge.vshop.VillagerShops:loadShops:269]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[19:36:31] [Server thread/INFO] [STDERR]: [de.dosmike.sponge.vshop.VillagerShops:loadShops:269]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[19:36:31] [Server thread/INFO] [STDERR]: [de.dosmike.sponge.vshop.VillagerShops:loadShops:269]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[19:36:31] [Server thread/INFO] [STDERR]: [de.dosmike.sponge.vshop.VillagerShops:loadShops:269]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[19:36:31] [Server thread/INFO] [STDERR]: [de.dosmike.sponge.vshop.VillagerShops:loadShops:269]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[19:36:31] [Server thread/INFO] [STDERR]: [de.dosmike.sponge.vshop.VillagerShops:loadShops:269]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[19:36:31] [Server thread/INFO] [STDERR]: [de.dosmike.sponge.vshop.VillagerShops:loadShops:269]: 	at net.minecraftforge.fml.common.LoadController.redirect$forgeImpl$PostEvent$zza000(LoadController.java:568)
[19:36:31] [Server thread/INFO] [STDERR]: [de.dosmike.sponge.vshop.VillagerShops:loadShops:269]: 	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
[19:36:31] [Server thread/INFO] [STDERR]: [de.dosmike.sponge.vshop.VillagerShops:loadShops:269]: 	at net.minecraftforge.fml.common.Loader.serverStarted(Loader.java:799)
[19:36:31] [Server thread/INFO] [STDERR]: [de.dosmike.sponge.vshop.VillagerShops:loadShops:269]: 	at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStarted(FMLCommonHandler.java:302)
[19:36:31] [Server thread/INFO] [STDERR]: [de.dosmike.sponge.vshop.VillagerShops:loadShops:269]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:488)
[19:36:31] [Server thread/INFO] [STDERR]: [de.dosmike.sponge.vshop.VillagerShops:loadShops:269]: 	at java.lang.Thread.run(Thread.java:748)
[19:36:31] [Server thread/INFO] [vshop]: Searching for updates...
[19:36:31] [Server thread/WARN] [vshop]: The automatic Version Checker for VillagerShops(vshop) is disabled!
[19:36:31] [Server thread/WARN] [vshop]: It is strongly recommended to activate the Version Checker to keep your server secure and up to date!
[19:36:31] [Server thread/INFO] [vshop]: User-Agent: VillagerShops/2.2.2 (Plugin by DosMike) SpongeAPI/7.1.0-20b5f1b02 SpongeForge/1.12.2-2838-7.1.7-RC3901 Minecraft/1.12.2
[19:36:31] [Server thread/INFO] [vshop]: VillagerShops is now ready!

The error came with the shop version 2.2.1 and 2.2.2 the others I have not tested.
The server would be a Sky Factory 4 server, so 1.12.2
Sponge Version: spongeforge-1.12.2-2838-7.1.7-RC3901

many thanks for your response

**Comment by DosMike** [comment] 2019-09-16 18:54
Thatnk you for the report.

Do you remember what items you had in that shop? Seems like some item could not properly load.

**Comment by bleihof** [comment] 2019-09-16 19:32
At one time it was a diamond sword and the other time it was a cobblestone generator from the modpack

I can also test other items if necessary.

**Comment by DosMike** [comment] 2019-09-17 16:49
if those trigger the bug that's enough. do you know from what mod the cobble gen was?

**Comment by bleihof** [comment] 2019-09-17 17:05
It is from the mod tinyprogressions. The version where Sky Factory 4 is in is tinyprogressions 1.12.2-3.3.32 release.

**Comment by DosMike** [comment] 2019-09-22 09:03
ok, so as of now it works on my test server... I'll try to play around with it a bit more but I can't currently see what's wrong.
I will add something that hopefully allows me to better analyse this kind of issue in the future

**Comment by bleihof** [comment] 2019-09-22 11:57
Until now it happened with every item, maybe the plugin is not compatible with the modpack or with another plugin that I have on the server. But I test that later, I disable all times except where your plugin needed and see if it still does not work.

**Comment by bleihof** [comment] 2019-09-22 14:24
Oke the error comes even if I have removed all plugins except for their 3 and EconomyLite and also the version 2.1.0 does not work.

I think it is the mod pack, maybe because it uses a too new Sponge version for your plugin?
Skyfactory 4 would be 1.12.2
Forge Version: forge-1.12.2-14.23.5.2836-universal.jar
Sponge Forge Version: spongeforge-1.12.2-2838-7.1.7-RC3901

**Comment by DosMike** [comment] 2019-09-23 07:41
Alright, I'll see if I get any results

**Comment by Pixxlated** [comment] 2019-11-28 02:25
I'm also getting the same issue, I restarted my server and the shop has reset itself, full of only vanilla items.

**Comment by DosMike** [comment] 2020-01-26 11:37
With the extensive logging introduced in version 2.3 this seems to be caused by multi-world servers that do not preload the world on startup when the server boots. This issue should be fixed with version 2.4.

**Closed by DosMike** 2020-01-26 11:37 UTC
Labels: bug, can't reproduce
